### ISSUE TITLE
Vapor == Qutheory

### ISSUE THREAD

**Issue by tanner0101** [czechboy0/swiftpm-packages-statistics#1]
Since we got the Vapor org that was previously being squatted on, Vapor package counts are fractured. 

Any way a special case could be added that would replace instances of qutheory with vapor or otherwise view them as equivalent?

**Comment by czechboy0** [comment]
Fixed.

Updated data: https://github.com/czechboy0/swiftpm-packages-statistics/commit/c4ba15ac0b864bc089ea120b244802c6f4b0e16f?diff=split
Fix: https://github.com/czechboy0/swift-package-crawler/commit/d09980e41af5189628d8fc50deeb09dd4a7766fd#diff-994e3e8d753fc446b5c9321f9f1f1ee9R10
